AWSTemplateFormatVersion: '2010-09-09'
Description: Event driven architecture application for workshop.
Resources:
  EDAWorkshopLambdaIAM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
  SendAssessmentsLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role: !GetAtt EDAWorkshopLambdaIAM.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";
          const ses = new SESClient({ region: "us-east-1" });
          export const handler = async (event) => {
              console.debug(event);
              const { toEmail, fromEmail } = event.detail;
              const companyName = event.companyName ?? "Company";

              const command = new SendEmailCommand({
                  Destination: {
                      ToAddresses: [toEmail],
                  },
                  Message: {
                      Body: {
                          Text: { Data: "You've been invited to take an assessment." },
                      },

                      Subject: { Data: `${companyName} has invited you to take an assessment` },
                  },
                  Source: fromEmail,
              });

              console.log('sending email...');
              let response = await ses.send(command);

              return response;
          };
      Runtime: nodejs20.x

  ScheduleInterviewLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs20.x
      Role: !GetAtt EDAWorkshopLambdaIAM.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";
          const ses = new SESClient({ region: "us-east-1" });
          export const handler = async (event) => {
            console.debug(event);
            const {toEmail, fromEmail} = event.detail;
            const companyName = event.companyName ?? "Company";

            const command = new SendEmailCommand({
              Destination: {
                ToAddresses: [toEmail],
              },
              Message: {
                Body: {
                  Text: { Data: "We'd like to schedule an interview with you. What does your availability look like?" },
                },

                Subject: { Data: `${companyName} has would like to schedule an interview` },
              },
              Source: fromEmail,
            });
            
            try {
              console.log('sending email...');
              let response = await ses.send(command);
              // process data.
              return response;
            }
            catch (error) {
              // error handling.
              console.error(error);
            }
            finally {
              // finally.
            }
            const response = {
              statusCode: 200,
              body: JSON.stringify('Schedule Interview Failed'),
            };
            return response;
          };
  
  SendOfferLetterLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs20.x
      Role: !GetAtt EDAWorkshopLambdaIAM.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";
          const ses = new SESClient({ region: "us-east-1" });
          export const handler = async (event) => {
            console.debug(event);
            const {toEmail, fromEmail} = event.detail;
            const companyName = event.companyName ?? "Company";

            const command = new SendEmailCommand({
              Destination: {
                ToAddresses: [toEmail],
              },
              Message: {
                Body: {
                  Text: { Data: "Welcome to the team. We are excited to extend an offer to you for the position you applied for. Please confirm and we hope to hear from you soon." },
                },

                Subject: { Data: `Congrats! ${companyName} has sent you an offer letter` },
              },
              Source: fromEmail,
            });
            
            try {
              console.log('sending email...');
              let response = await ses.send(command);
              // process data.
              return response;
            }
            catch (error) {
              // error handling.
              console.error(error);
            }
            finally {
              // finally.
            }
            const response = {
              statusCode: 200,
              body: JSON.stringify('Send Offer Letter Failed'),
            };
            return response;
          };
  EDAWorkshopEventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: EDAWorkshopEventBus
  SendAssessmentRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule to send assessment email
      EventBusName: !Ref EDAWorkshopEventBus
      EventPattern:
        detail-type:
          - "send-assessment"
      State: ENABLED
      Targets:
        - Arn: !GetAtt SendAssessmentsLambdaFunction.Arn
          Id: SendAssessmentsLambdaFunction
  ScheduleInterviewRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule to schedule interview
      EventBusName: !Ref EDAWorkshopEventBus
      EventPattern:
        detail-type:
          - "schedule-interview"
      State: ENABLED
      Targets:
        - Arn: !GetAtt ScheduleInterviewLambdaFunction.Arn
          Id: ScheduleInterviewLambdaFunction
  SendOfferLetterRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule to send offer letter
      EventBusName: !Ref EDAWorkshopEventBus
      EventPattern:
        detail-type:
          - "send-offer-letter"
      State: ENABLED
      Targets:
        - Arn: !GetAtt SendOfferLetterLambdaFunction.Arn
          Id: SendOfferLetterLambdaFunction
          