AWSTemplateFormatVersion: '2010-09-09'
Description: Event driven architecture application for workshop.
Resources:
  EDAWorkshopLambdaIAM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
  SendAssessmentsLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs20.x
      Role: !GetAtt EDAWorkshopLambdaIAM.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";
          const ses = new SESClient({ region: "us-east-1" });
          export const handler = async (event) => {
            console.debug(event);
            const {toEmail, fromEmail} = event.detail;
            const companyName = event.companyName ?? "Company";

            const command = new SendEmailCommand({
              Destination: {
                ToAddresses: [toEmail],
              },
              Message: {
                Body: {
                  Text: { Data: "We'd like to schedule an interview with you. What does your availability look like?" },
                },

                Subject: { Data: `${companyName} has would like to schedule an interview` },
              },
              Source: fromEmail,
            });
            
            try {
              console.log('sending email...');
              let response = await ses.send(command);
              // process data.
              return response;
            }
            catch (error) {
              // error handling.
              console.error(error);
            }
            finally {
              // finally.
            }
            const response = {
              statusCode: 200,
              body: JSON.stringify('Schedule Interview Failed'),
            };
            return response;
          };
      